// export const ADD_ARTICLE = "ADD_ARTICLE";
// export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
// export const ADD_USER = "ADD_USER";
// export const EDIT_USER = "EDIT_USER";
// export const REMOVE_USER = "REMOVE_USER";
// export const LOGIN_USER_START = "LOGIN_USER_START";
// export const LOGIN_USER_FINISH = "LOGIN_USER_FINISH";
// export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

enum actionTypes {
  ADD_ARTICLE = "ADD_ARTICLE",
  REMOVE_ARTICLE = "REMOVE_ARTICLE",
  ADD_USER = "ADD_USER",
  EDIT_USER = "EDIT_USER",
  REMOVE_USER = "REMOVE_USER",
  LOGIN_USER_START = "LOGIN_USER_START",
  LOGIN_USER_FINISH = "LOGIN_USER_FINISH",
  LOGIN_USER_FAIL = "LOGIN_USER_FAIL",
}

export default actionTypes;
